FROM node:12.13.1-alpine3.9

LABEL MAINTAINER="BELAYET HOSSAIN"
LABEL EMAIL = "2020belayethossain@gmail.com"
LABEL VERSION = 1.0

WORKDIR /opt/app/src/client

# RUN apk update && apk add yarn

# COPY package.json .
# RUN cd src
RUN yarn

# COPY . .




